🥅 Error handling added

diff --git a/images/befunge/Dockerfile.base b/images/befunge/Dockerfile.base
--- a/images/befunge/Dockerfile.base
+++ b/images/befunge/Dockerfile.base
@@ -4,16 +4,18 @@ SHELL ["/bin/bash", "-lc"]
 
 WORKDIR /app
 
-COPY /app/main.bf .
+COPY app .
 
-ONBUILD RUN apt update; apt-get -y install make
-
-ONBUILD RUN git clone https://github.com/catseye/Befunge-93.git && \
+ONBUILD RUN if [ -f main.bf ]; then \
+    apt update; apt-get -y install make && \
+    git clone https://github.com/catseye/Befunge-93.git && \
     cd Befunge-93 && \
     make && \
-    mv bin/bef ../
-
-
-ONBUILD RUN rm -rf Befunge-93
+    mv bin/bef ../ && \
+    rm -rf Befunge-93 \
+    else \
+        echo "main.bf not found."; \
+        exit 1; \
+    fi
 
 ONBUILD CMD ["./bef", "main.bf"]
diff --git a/images/befunge/Dockerfile.standalone b/images/befunge/Dockerfile.standalone
--- a/images/befunge/Dockerfile.standalone
+++ b/images/befunge/Dockerfile.standalone
@@ -4,19 +4,20 @@ SHELL ["/bin/bash", "-lc"]
 
 WORKDIR /app
 
-COPY /app/main.bf .
+COPY app .
 
 
-RUN apt update; apt-get -y install make
-
-
-RUN git clone https://github.com/catseye/Befunge-93.git && \
+RUN if [ -f main.bf ]; then \
+    apt update; apt-get -y install make && \
+    git clone https://github.com/catseye/Befunge-93.git && \
     cd Befunge-93 && \
     make && \
-    mv bin/bef ../
-
-
-RUN rm -rf Befunge-93
+    mv bin/bef ../ && \
+    rm -rf Befunge-93 \
+    else \
+        echo "main.bf not found."; \
+        exit 1; \
+    fi
 
 
 CMD ["./bef", "main.bf"]
diff --git a/images/python/Dockerfile.base b/images/python/Dockerfile.base
--- a/images/python/Dockerfile.base
+++ b/images/python/Dockerfile.base
@@ -4,10 +4,14 @@ SHELL ["/bin/bash", "-lc"]
 
 WORKDIR /app
 
-ONBUILD COPY requirements.txt .
+ONBUILD COPY app .
 
-ONBUILD RUN pip install -r requirements.txt
+ONBUILD RUN if [ -f requirements.txt ]; then \
+    pip install -r requirements.txt \
+    else \
+        echo "requirements.txt not found."; \
+        exit 1; \
+    fi
 
-ONBUILD COPY app/ .
 
 ONBUILD CMD ["python", "-m", "app"]
diff --git a/images/python/Dockerfile.standalone b/images/python/Dockerfile.standalone
--- a/images/python/Dockerfile.standalone
+++ b/images/python/Dockerfile.standalone
@@ -4,10 +4,14 @@ SHELL ["/bin/bash", "-lc"]
 
 WORKDIR /app
 
-COPY requirements.txt .
+COPY app .
 
-RUN pip install -r requirements.txt
+RUN if [ -f requirements.txt ]; then \
+    pip install -r requirements.txt \
+    else \
+        echo "requirements.txt not found."; \
+        exit 1; \
+    fi
 
-COPY app/ .
 
 CMD ["python", "-m", "app"]
